import { useGLTF } from '@react-three/drei'
import { shirt_baked_scene } from '../assets/models'
import { useFrame } from '@react-three/fiber'
import { useSnapshot } from 'valtio'
import state from '../store'
import { easing } from 'maath'

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
const ShirtBaked: React.FC = (props) => {
  const snap = useSnapshot(state)
  const { nodes, materials } = useGLTF(shirt_baked_scene)
  const shirtMesh = nodes.T_Shirt_male as THREE.Mesh
  const lambertMaterial = materials.lambert1 as THREE.MeshLambertMaterial

  useFrame((_, delta) =>
    easing.dampC(lambertMaterial.color, snap.color, 0.25, delta),
  )

  return (
    <group {...props} dispose={null} visible={snap.currentModel ? true : false}>
      <mesh
        castShadow
        receiveShadow
        material={materials.lambert1}
        geometry={shirtMesh.geometry}
        material-roughness={1}
      />
    </group>
  )
}
useGLTF.preload(shirt_baked_scene)
export default ShirtBaked
