import { useGLTF } from '@react-three/drei'
import { shirt_baked_scene2 } from '../assets/models'
import state from '../store'
import { useSnapshot } from 'valtio'
import { useFrame } from '@react-three/fiber'
import { easing } from 'maath'
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: lod0 (https://sketchfab.com/lod0_it)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/man-shirt-fba56a5716734e218d32b66063f911d5
Title: Man Shirt
*/

const ShirtFormal: React.FC = () => {
  const { nodes, materials } = useGLTF(shirt_baked_scene2)
  const snap = useSnapshot(state)
  const changeMaterialColor = (material: any, color: string) => {
    if (material) {
      material.color.set(color)
    }
  }

  useFrame((_, delta) => {
    easing.dampC(
      (materials.PT_FABRIC_FRONT_4564 as THREE.MeshLambertMaterial).color,
      snap.color,
      0.25,
      delta,
    )
    easing.dampC(
      (materials.Cotton_01_FRONT_4527 as THREE.MeshLambertMaterial).color,
      snap.color,
      0.25,
      delta,
    )
    easing.dampC(
      (materials.Collo__Maniche_FRONT_4532 as THREE.MeshLambertMaterial).color,
      snap.color,
      0.25,
      delta,
    )
  })

  // Change the color of the desired materials
  changeMaterialColor(materials.Material10826564, 'black') //? This is the color of the shirt buttons
  return (
    <group
      dispose={null}
      position={[0, 2, -5]}
      scale={[0.01, 0.01, 0.01]}
      visible={!snap.currentModel ? true : false}
    >
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.Object_2 as THREE.Mesh).geometry}
          material={materials.PT_FABRIC_FRONT_4564}
          material-roughness={1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.Object_3 as THREE.Mesh).geometry}
          material={materials.PT_FABRIC_FRONT_4564}
          material-roughness={1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.Object_4 as THREE.Mesh).geometry}
          material={materials.Material10826564}
          material-roughness={1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.Object_5 as THREE.Mesh).geometry}
          material={materials.Material10826564}
          material-roughness={1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.Object_6 as THREE.Mesh).geometry}
          material={materials.Cotton_01_FRONT_4527}
          material-roughness={1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.Object_7 as THREE.Mesh).geometry}
          material={materials.Cotton_01_FRONT_4527}
          material-roughness={1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.Object_8 as THREE.Mesh).geometry}
          material={materials.Cotton_01_FRONT_4527}
          material-roughness={1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.Object_9 as THREE.Mesh).geometry}
          material={materials.Collo__Maniche_FRONT_4532}
          material-roughness={1}
        />
      </group>
    </group>
  )
}
useGLTF.preload(shirt_baked_scene2)

export default ShirtFormal
