import { useGLTF } from '@react-three/drei'
import { shirt_baked_scene2 } from '../assets/models'
const ShirtHoodie: React.FC = () => {
  /*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: lod0 (https://sketchfab.com/lod0_it)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/man-shirt-fba56a5716734e218d32b66063f911d5
Title: Man Shirt
*/

  const { nodes, materials } = useGLTF(shirt_baked_scene2)
  const changeMaterialColor = (material: any, color: string) => {
    if (material) {
      material.color.set(color)
    }
  }

  // Change the color of the desired materials
  changeMaterialColor(materials.Cotton_01_FRONT_4527, 'red')
  return (
    <group dispose={null} position={[0, 2, -5]} scale={[0.02, 0.02, 0.02]}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2.geometry}
          material={materials.PT_FABRIC_FRONT_4564}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_3.geometry}
          material={materials.PT_FABRIC_FRONT_4564}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_4.geometry}
          material={materials.Material10826564}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_5.geometry}
          material={materials.Material10826564}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6.geometry}
          material={materials.Cotton_01_FRONT_4527}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_7.geometry}
          material={materials.Cotton_01_FRONT_4527}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_8.geometry}
          material={materials.Cotton_01_FRONT_4527}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_9.geometry}
          material={materials.Collo__Maniche_FRONT_4532}
        />
      </group>
    </group>
  )
}

export default ShirtHoodie
